import Navbar from '@components/Navbar/page';
import '@styles/globals.css';
import cx from '@styles/MainStyle.module.scss';

export const metadata = {
    title: 'Portfolio',
    description: 'Generated by create next app',
}

const RootLayout = ({children,}: {children: React.ReactNode}) => {
    return (
        <html lang="en">
            <body>
                <div className={cx['bg-page']}>
                    <Navbar />
                    <div className={cx['container']}>
                        <div className="mx-auto">
                            <main>
                                {children}
                            </main>
                        </div>
                    </div>
                </div>
            </body>
        </html>
    )
}

export default RootLayout;